name: QCommE2E
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pytorch
  - matplotlib
  - pyyaml
  - tqdm
  - pytest
  - pip
  - pip:
    - qutip>=5.0
    - pennylane
    - tensorboard
    - pylint
    - black
    - jupyter
    - ipywidgets
